### ISSUE TITLE
Sync-reconciliation: the fork→overlay sync clobbers amicode-side fixes (#929's fix regressed by ff7b69c8; the diff_version fix owes a fork mirror)

### ISSUE THREAD

**Issue by aarontrowbridge** [harmoniqs/amicode#964]
> [!IMPORTANT]
> **Problem** — The Sep 9 overlay sync (ff7b69c8, "Sync app overlay from merged opencode local/amicode") **overwrote amicode-side fixes with stale fork state**: #929's 3-arg `promptDesignPlaceholder(mode(), placeholder(), t)` fix (59b447e7, same day) was regressed back to the fork's 2-arg call — every non-shell composer render threw "n is not a function". Aaron hit it live post-cutover (2026-09-10), fixed it in the deployed dist-app (the hub serves the restored 3-arg call), but **main's overlay still carries the regressed call** — the next dist rebuild regresses the UI again. Aaron's second flag: the diff_version reconciliation (#832) needs mirroring to the fork (the sync source), or the next sync drags it back too.
> **Root cause (Aaron)**: the fork-sync workflow has no amicode-fixes-are-canonical rule — the sync direction (fork → overlay) treats the fork as authoritative even where amicode fixed what the fork never had. Same family as #842 (the overlay_sync hazard).

## Work items
- [ ] **Restore #929's fix on main** — the 3-arg call + the comment naming the regressing sync (Aaron's deployed fix, committed this time); regression test: the composer renders non-shell without throwing.
- [ ] **Mirror to the fork (harmoniqs/opencode, the sync source)**: the 3-arg fix (verified absent — the 2-arg call at prompt-input-v2.tsx:148 on local/amicode) + the diff_version reconciliation (Aaron's check). The fork stays the sync source until the sync tooling is fixed — it must carry what the overlay carries.
- [ ] **The pre-sync rule**: before any fork→overlay sync, diff the fork's copies against amicode's fixes (the known-fixed list: #929's translation callback, the diff_version reconciliation, the #832 locale/exportTrace set) — a sync that would revert an amicode-side fix fails loudly. The mechanical form: extend the #842/#850 sweep (a guard test over the overlay's known-fixed hunks).
- [ ] **Sweep**: what ELSE did ff7b69c8 (and the Sep 9 sync) clobber? Diff the fork's overlay copies against amicode's post-#832/#929 state — the known-fixed hunks verified present, anything else surfaced.

Aaron's live fix is the reference implementation (deployed on erlich's dist-app, verified containing the restored 3-arg call).
